### PR TITLE
Updated link to posobota video

### PR DESCRIPTION
**Pull request by jkuchar**

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Thank you very much! I already updated the file in a meantime so this can be closed. 😎

**Comment by jkuchar** [comment]
I cannot find how, I'm sorry.

**Comment by mrtnzlml** [comment]
There should be a button available for you with a label "Close pull request": https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request

Unfortunately, I cannot do it on your behalf because this PR is into your fork (`jkuchar/mrtnzlml`), not my repository (`mrtnzlml/mrtnzlml`). In other words, I do not have permission to close this PR because I do not own the fork.

**Comment by jkuchar** [comment]
Cool, I haven't found it on mobile app. Have a great time! 🙂

**Pull request closed without merging**
